apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends
  namespace: sandbox
  name: techtrends
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techtrends
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
        - image: k4568/techtrends:latest
          imagePullPolicy: IfNotPresent
          name: techtrends
          ports:
            - containerPort: 3111
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /healthz
              port: 3111
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /healthz
              port: 3111
          resources:
            requests:
              cpu: '250m'
              memory: '64Mi'
            limits:
              cpu: '500m'
              memory: '128Mi'
