apiVersion: v1
kind: Service
metadata:
  labels:
    app: techtrends
  namespace: sandbox
  name: techtrends
spec:
  ports:
    - port: 4111
      targetPort: 3111
      protocol: TCP
  selector:
    app: techtrends
  type: ClusterIP
